services:
  smee:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - WEBHOOK_PROXY_URL=$WEBHOOK_PROXY_URL
    command:
      - --url
      - $WEBHOOK_PROXY_URL
      - --path
      - /post-receive
      - --port
      - "8000"

